### ISSUE TITLE
gettext and glib need to be bumped

### ISSUE THREAD

**Issue by prototype99** [orsonteodoro/muslx32#6]
they rely on an eclass that has been removed

**Comment by orsonteodoro** [comment]
gettext was updated, but glib was dropped.  Use glib from the musl overlay (https://github.com/gentoo/musl).  I updated the eclasses for EAPI compatibility, but may break with 17.1 profile lib changes.

**Comment by prototype99** [comment]
oh of course, you make oiledmachine! that is actually one of my favourites. but yeah that all looks fine so I'll close it, any 17.1 issues would probably be a new issue (also still using 17.0 for now)
